travis:
  secure:
    BINSTAR_TOKEN: BxVYqcvoSOVS5NxT3+AN6IFI9YNEnBKC8443rnCRI6iljaj0iJ3+uPeinbidmAP1C/L257/tm4rdCPGpgZQJSNPmRrSfb/BJVLYqTd+9WQ1K68VbKoI1WdQsv5v3nN/ToUE+cehop+/J2fiW6PIlhLZBFTv3VqxSmeMpRQqW5bQ8VZ75PQ7ctBpsTBFnvI1eoB/ZqBbayBH+9E/m7YBPeGyfBf4Y38WZ29sI1LVD/deIuNkw2RyC9AqGSiQAMRPwjojGAJhuPXM5iTI7PFjKbSf2xEmkfwTGFw/i21OhFDtbNlXHoSrnLOt33fb1HZ9c7RAhWHa6VC71YrWXKqSG8+HDzwMrEz0xFyBRQ1k7MLqAi5lN8HRWV4ARDnLi5aAN5ElZ5Y1ODW1zCPiF9IWXFOK3JsNZmZ9+53goh5+yzsA/OrVAB7pL7NevNvRmpvKZ0DQ8JQz4On56bqISjgq8d52QbZsYqjQMw9HwTTmcmC/eoKhk6WrrFuecE2Mg/j+xdniMCGtpY0XJ4CbHCAKWTKf2ZXtdm8T3rkK2i0b9/0p8iqHMWiYt5QgQn6wP1D7Z7eBPy9iBYhfrRiYeImi0+82WGAe81xq1aJ95ZqHyt1uQv2Bk69eDj1scpW2YQiEqiLjaCnsz++wvoOwSvAOr5pUwqMd43GQz9tZqkww5o7g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
